{{ 
    config(
        materialized='table'
    )
}}

{% set end_date = get_future_date(2) %}

WITH date_dimension AS (
    {{ dbt_date.get_date_dimension(start_date='2018-01-01', end_date=end_date) }}
),

future_date AS (
    SELECT
        CAST('9999-12-31' AS DATE) AS DATE_DAY,
        CAST('9999-12-30' AS DATE) AS PRIOR_DATE_DAY,
        CAST('10000-01-01' AS DATE) AS NEXT_DATE_DAY,
        CAST('9998-12-31' AS DATE) AS PRIOR_YEAR_DATE_DAY,
        CAST('9997-12-31' AS DATE) AS PRIOR_YEAR_OVER_YEAR_DATE_DAY,
        CAST(7 AS NUMBER(38,0)) AS DAY_OF_WEEK,
        CAST(7 AS NUMBER(38,0)) AS DAY_OF_WEEK_ISO,
        CAST('domingo' AS VARCHAR) AS DAY_OF_WEEK_NAME,
        CAST('dom' AS VARCHAR) AS DAY_OF_WEEK_NAME_SHORT,
        CAST(31 AS NUMBER(38,0)) AS DAY_OF_MONTH,
        CAST(365 AS NUMBER(38,0)) AS DAY_OF_YEAR,
        CAST('9999-12-26' AS DATE) AS WEEK_START_DATE,
        CAST('10000-01-01' AS DATE) AS WEEK_END_DATE,
        CAST('9998-12-27' AS DATE) AS PRIOR_YEAR_WEEK_START_DATE,
        CAST('9999-01-02' AS DATE) AS PRIOR_YEAR_WEEK_END_DATE,
        CAST(52 AS NUMBER(38,0)) AS WEEK_OF_YEAR,
        CAST('9999-12-25' AS DATE) AS ISO_WEEK_START_DATE,
        CAST('10000-01-01' AS DATE) AS ISO_WEEK_END_DATE,
        CAST('9998-12-26' AS DATE) AS PRIOR_YEAR_ISO_WEEK_START_DATE,
        CAST('9999-01-01' AS DATE) AS PRIOR_YEAR_ISO_WEEK_END_DATE,
        CAST(52 AS NUMBER(38,0)) AS ISO_WEEK_OF_YEAR,
        CAST('9999-W52' AS VARCHAR) AS ISO_YEAR_WEEK,
        CAST(52 AS NUMBER(38,0)) AS PRIOR_YEAR_WEEK_OF_YEAR,
        CAST(52 AS NUMBER(38,0)) AS PRIOR_YEAR_ISO_WEEK_OF_YEAR,
        CAST(12 AS NUMBER(38,0)) AS MONTH_OF_YEAR,
        CAST('diciembre' AS VARCHAR) AS MONTH_NAME,
        CAST('dic' AS VARCHAR) AS MONTH_NAME_SHORT,
        CAST('9999-12-01' AS DATE) AS MONTH_START_DATE,
        CAST('9999-12-31' AS DATE) AS MONTH_END_DATE,
        CAST('9998-12-01' AS DATE) AS PRIOR_YEAR_MONTH_START_DATE,
        CAST('9998-12-31' AS DATE) AS PRIOR_YEAR_MONTH_END_DATE,
        CAST(4 AS NUMBER(38,0)) AS QUARTER_OF_YEAR,
        CAST('9999-10-01' AS DATE) AS QUARTER_START_DATE,
        CAST('9999-12-31' AS DATE) AS QUARTER_END_DATE,
        CAST(9999 AS NUMBER(38,0)) AS YEAR_NUMBER,
        CAST('9999-01-01' AS DATE) AS YEAR_START_DATE,
        CAST('9999-12-31' AS DATE) AS YEAR_END_DATE
)

SELECT * FROM date_dimension
UNION ALL
SELECT * FROM future_date